global proc unityConfigure(
    string $unityProject,
    string $unityFbxExportSettings,
    string $unityFbxImportSettings,
    int $headless)
{
    // configure plugin settings
    optionVar -stringValue "UnityProject" $unityProject;
    optionVar -stringValue "UnityFbxExportSettings" $unityFbxExportSettings;
    optionVar -stringValue "UnityFbxImportSettings" $unityFbxImportSettings;
    optionVar -intValue "UnityFbxForMaya_Headless" $headless;

    return;
}