//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Unity.FbxSdk {

public class Globals {
  public static FbxDataType FbxUndefinedDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxUndefinedDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxBoolDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxBoolDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxCharDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxCharDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxUCharDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxUCharDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxShortDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxShortDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxUShortDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxUShortDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxIntDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxIntDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxUIntDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxUIntDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxLongLongDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxLongLongDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxULongLongDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxULongLongDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxFloatDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxFloatDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxHalfFloatDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxHalfFloatDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxDoubleDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxDoubleDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxDouble2DT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxDouble2DT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxDouble3DT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxDouble3DT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxDouble4DT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxDouble4DT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxDouble4x4DT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxDouble4x4DT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxEnumDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxEnumDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxStringDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxStringDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxTimeDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxTimeDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxReferenceDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxReferenceDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxBlobDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxBlobDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxDistanceDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxDistanceDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxDateTimeDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxDateTimeDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxColor3DT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxColor3DT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxColor4DT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxColor4DT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxCompoundDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxCompoundDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxReferenceObjectDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxReferenceObjectDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxReferencePropertyDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxReferencePropertyDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxVisibilityDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxVisibilityDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxVisibilityInheritanceDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxVisibilityInheritanceDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxUrlDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxUrlDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxXRefUrlDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxXRefUrlDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxTranslationDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxTranslationDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxRotationDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxRotationDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxScalingDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxScalingDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxQuaternionDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxQuaternionDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxLocalTranslationDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxLocalTranslationDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxLocalRotationDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxLocalRotationDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxLocalScalingDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxLocalScalingDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxLocalQuaternionDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxLocalQuaternionDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxTransformMatrixDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxTransformMatrixDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxTranslationMatrixDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxTranslationMatrixDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxRotationMatrixDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxRotationMatrixDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxScalingMatrixDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxScalingMatrixDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxMaterialEmissiveDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxMaterialEmissiveDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxMaterialEmissiveFactorDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxMaterialEmissiveFactorDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxMaterialAmbientDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxMaterialAmbientDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxMaterialAmbientFactorDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxMaterialAmbientFactorDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxMaterialDiffuseDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxMaterialDiffuseDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxMaterialDiffuseFactorDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxMaterialDiffuseFactorDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxMaterialBumpDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxMaterialBumpDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxMaterialNormalMapDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxMaterialNormalMapDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxMaterialTransparentColorDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxMaterialTransparentColorDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxMaterialTransparencyFactorDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxMaterialTransparencyFactorDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxMaterialSpecularDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxMaterialSpecularDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxMaterialSpecularFactorDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxMaterialSpecularFactorDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxMaterialShininessDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxMaterialShininessDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxMaterialReflectionDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxMaterialReflectionDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxMaterialReflectionFactorDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxMaterialReflectionFactorDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxMaterialDisplacementDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxMaterialDisplacementDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxMaterialVectorDisplacementDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxMaterialVectorDisplacementDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxMaterialCommonFactorDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxMaterialCommonFactorDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxMaterialCommonTextureDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxMaterialCommonTextureDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxLayerElementUndefinedDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxLayerElementUndefinedDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxLayerElementNormalDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxLayerElementNormalDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxLayerElementBinormalDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxLayerElementBinormalDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxLayerElementTangentDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxLayerElementTangentDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxLayerElementMaterialDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxLayerElementMaterialDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxLayerElementTextureDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxLayerElementTextureDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxLayerElementPolygonGroupDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxLayerElementPolygonGroupDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxLayerElementUVDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxLayerElementUVDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxLayerElementVertexColorDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxLayerElementVertexColorDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxLayerElementSmoothingDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxLayerElementSmoothingDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxLayerElementCreaseDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxLayerElementCreaseDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxLayerElementHoleDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxLayerElementHoleDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxLayerElementUserDataDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxLayerElementUserDataDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxLayerElementVisibilityDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxLayerElementVisibilityDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxAliasDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxAliasDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxPresetsDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxPresetsDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxStatisticsDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxStatisticsDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxTextLineDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxTextLineDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxUnitsDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxUnitsDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxWarningDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxWarningDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxWebDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxWebDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxActionDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxActionDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxCameraIndexDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxCameraIndexDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxCharPtrDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxCharPtrDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxConeAngleDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxConeAngleDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxEventDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxEventDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxFieldOfViewDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxFieldOfViewDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxFieldOfViewXDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxFieldOfViewXDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxFieldOfViewYDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxFieldOfViewYDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxFogDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxFogDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxHSBDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxHSBDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxIKReachTranslationDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxIKReachTranslationDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxIKReachRotationDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxIKReachRotationDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxIntensityDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxIntensityDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxLookAtDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxLookAtDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxOcclusionDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxOcclusionDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxOpticalCenterXDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxOpticalCenterXDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxOpticalCenterYDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxOpticalCenterYDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxOrientationDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxOrientationDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxRealDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxRealDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxRollDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxRollDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxScalingUVDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxScalingUVDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxShapeDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxShapeDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxStringListDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxStringListDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxTextureRotationDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxTextureRotationDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxTimeCodeDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxTimeCodeDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxTimeWarpDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxTimeWarpDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxTranslationUVDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxTranslationUVDT_get(), false);
      return ret;
    } 
  }

  public static FbxDataType FbxWeightDT {
    get {
      FbxDataType ret = new FbxDataType(GlobalsPINVOKE.FbxWeightDT_get(), false);
      return ret;
    } 
  }

  internal static bool IsValidColor(FbxColor c) {
    bool ret = GlobalsPINVOKE.IsValidColor(c);
    return ret;
  }


  public delegate bool FbxProgressCallback(float percentage, string status);

  public static readonly int FBXSDK_PROPERTY_ID_NULL = GlobalsPINVOKE.FBXSDK_PROPERTY_ID_NULL_get();
  public static readonly int FBXSDK_PROPERTY_ID_ROOT = GlobalsPINVOKE.FBXSDK_PROPERTY_ID_ROOT_get();
  public static readonly string IOSROOT = GlobalsPINVOKE.IOSROOT_get();
  public static readonly string IMP_FBX_GLOBAL_SETTINGS = GlobalsPINVOKE.IMP_FBX_GLOBAL_SETTINGS_get();
  public static readonly string IMP_FBX_MATERIAL = GlobalsPINVOKE.IMP_FBX_MATERIAL_get();
  public static readonly string IMP_FBX_TEXTURE = GlobalsPINVOKE.IMP_FBX_TEXTURE_get();
  public static readonly string IMP_FBX_ANIMATION = GlobalsPINVOKE.IMP_FBX_ANIMATION_get();
  public static readonly string IMP_FBX_EXTRACT_EMBEDDED_DATA = GlobalsPINVOKE.IMP_FBX_EXTRACT_EMBEDDED_DATA_get();
  public static readonly string EXP_FBX_GLOBAL_SETTINGS = GlobalsPINVOKE.EXP_FBX_GLOBAL_SETTINGS_get();
  public static readonly string EXP_FBX_MATERIAL = GlobalsPINVOKE.EXP_FBX_MATERIAL_get();
  public static readonly string EXP_FBX_TEXTURE = GlobalsPINVOKE.EXP_FBX_TEXTURE_get();
  public static readonly string EXP_FBX_ANIMATION = GlobalsPINVOKE.EXP_FBX_ANIMATION_get();
  public static readonly string EXP_FBX_EMBEDDED = GlobalsPINVOKE.EXP_FBX_EMBEDDED_get();
  public static readonly string FBXSDK_SHADING_LANGUAGE_HLSL = GlobalsPINVOKE.FBXSDK_SHADING_LANGUAGE_HLSL_get();
  public static readonly string FBXSDK_SHADING_LANGUAGE_GLSL = GlobalsPINVOKE.FBXSDK_SHADING_LANGUAGE_GLSL_get();
  public static readonly string FBXSDK_SHADING_LANGUAGE_CGFX = GlobalsPINVOKE.FBXSDK_SHADING_LANGUAGE_CGFX_get();
  public static readonly string FBXSDK_SHADING_LANGUAGE_SFX = GlobalsPINVOKE.FBXSDK_SHADING_LANGUAGE_SFX_get();
  public static readonly string FBXSDK_SHADING_LANGUAGE_MRSL = GlobalsPINVOKE.FBXSDK_SHADING_LANGUAGE_MRSL_get();
  public static readonly string FBXSDK_RENDERING_API_DIRECTX = GlobalsPINVOKE.FBXSDK_RENDERING_API_DIRECTX_get();
  public static readonly string FBXSDK_RENDERING_API_OPENGL = GlobalsPINVOKE.FBXSDK_RENDERING_API_OPENGL_get();
  public static readonly string FBXSDK_RENDERING_API_MENTALRAY = GlobalsPINVOKE.FBXSDK_RENDERING_API_MENTALRAY_get();
  public static readonly string FBXSDK_RENDERING_API_PREVIEW = GlobalsPINVOKE.FBXSDK_RENDERING_API_PREVIEW_get();
  public static readonly string FBXSDK_CURVENODE_TRANSFORM = GlobalsPINVOKE.FBXSDK_CURVENODE_TRANSFORM_get();
  public static readonly string FBXSDK_CURVENODE_TRANSLATION = GlobalsPINVOKE.FBXSDK_CURVENODE_TRANSLATION_get();
  public static readonly string FBXSDK_CURVENODE_ROTATION = GlobalsPINVOKE.FBXSDK_CURVENODE_ROTATION_get();
  public static readonly string FBXSDK_CURVENODE_SCALING = GlobalsPINVOKE.FBXSDK_CURVENODE_SCALING_get();
  public static readonly string FBXSDK_CURVENODE_COMPONENT_X = GlobalsPINVOKE.FBXSDK_CURVENODE_COMPONENT_X_get();
  public static readonly string FBXSDK_CURVENODE_COMPONENT_Y = GlobalsPINVOKE.FBXSDK_CURVENODE_COMPONENT_Y_get();
  public static readonly string FBXSDK_CURVENODE_COMPONENT_Z = GlobalsPINVOKE.FBXSDK_CURVENODE_COMPONENT_Z_get();
  public static readonly string FBXSDK_CURVENODE_COLOR = GlobalsPINVOKE.FBXSDK_CURVENODE_COLOR_get();
  public static readonly string FBXSDK_CURVENODE_COLOR_RED = GlobalsPINVOKE.FBXSDK_CURVENODE_COLOR_RED_get();
  public static readonly string FBXSDK_CURVENODE_COLOR_GREEN = GlobalsPINVOKE.FBXSDK_CURVENODE_COLOR_GREEN_get();
  public static readonly string FBXSDK_CURVENODE_COLOR_BLUE = GlobalsPINVOKE.FBXSDK_CURVENODE_COLOR_BLUE_get();
  public static readonly string FBXSDK_CAMERA_PERSPECTIVE = GlobalsPINVOKE.FBXSDK_CAMERA_PERSPECTIVE_get();
  public static readonly int FBX_NO_SECTION = GlobalsPINVOKE.FBX_NO_SECTION_get();
  public static readonly int FBX_MAIN_SECTION = GlobalsPINVOKE.FBX_MAIN_SECTION_get();
  public static readonly int FBX_EXTENSION_SECTION_0 = GlobalsPINVOKE.FBX_EXTENSION_SECTION_0_get();

}

}
